[binaries]
c = toolchain + '/bin/aarch64-linux-android21-clang'
cpp = toolchain + '/bin/aarch64-linux-android21-clang++'
ar = toolchain + '/bin/llvm-ar'
strip = toolchain + '/bin/llvm-strip'

[constants]
#https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
ndk_path = '/Users/runner/Library/Android/sdk/ndk/29.0.14206865'
toolchain = ndk_path + '/toolchains/llvm/prebuilt/darwin-armv8'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'armv8-a'
endian = 'little'
