#!/bin/sh

case $2 in
link)

	case $1 in
		SunOS | solaris)
			echo '-lsocket -lnsl';
		;;
		BeOS)
			echo '-lsocket -lbind -lbsd';
		;;
		Haiku)
			echo '-lnetwork';
		;;
		windows32)
			echo '-lws2_32 -liphlpapi';
		;;
	esac
	;;
cflags)
	case $1 in
		BeOS)
			echo '-Dsocklen_t=int';
		;;
	esac
;;
*)
;;
esac
