#!/bin/sh

case $2 in
link)

	case $1 in
		SunOS | solaris)
			echo '-lsocket -lnsl';
		;;
		BeOS)
			echo '-lsocket -lbind -lbsd';
		;;
		Haiku)
			echo '-lnetwork';
		;;
		windows32)
			echo '-lws2_32 -liphlpapi';
		;;
		Linux)
			FLAGS="";
			[ -e /usr/include/selinux/selinux.h ] && FLAGS="$FLAGS -lselinux";
			[ -e /usr/include/systemd/sd-daemon.h ] && FLAGS="$FLAGS -lsystemd-daemon";
			echo $FLAGS;
		;;
	esac
	;;
cflags)
	case $1 in
		windows32)
			echo '-DWINVER=0x0501';
		;;
		BeOS)
			echo '-Dsocklen_t=int';
		;;
		Linux)
			FLAGS="-D_GNU_SOURCE"
			[ -e /usr/include/selinux/selinux.h ] && FLAGS="$FLAGS -DHAVE_SETCON";
			[ -e /usr/include/systemd/sd-daemon.h ] && FLAGS="$FLAGS -DHAVE_SYSTEMD";
			echo $FLAGS;
		;;
	esac
;;
*)
;;
esac
