#!/bin/sh

case $1 in
link)

	case `uname` in
		SunOS | solaris)
			echo '-lsocket -lnsl';
		;;
		BeOS)
			echo '-lsocket -lbind -lbsd';
		;;
		Haiku)
			echo '-lnetwork';
		;;
		windows32)
			echo '-lplibc -lws2_32';
		;;
	esac
	;;
cflags)
	case `uname` in
		BeOS)
			echo '-Dsocklen_t=int';
		;;
	esac
;;
*)
;;
esac
