name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7
    - name: install deps
      run: brew install check meson
    - name: setup
      run: meson setup build
    - name: build
      working-directory: build
      run: ninja
    - name: run tests
      working-directory: build
      run: ninja test

  build-android:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7
    - name: install deps
      run: brew install check meson
    - name: meson setup
      run: meson setup build-android --cross-file .github/macos-android-aarch64.ini
    - name: build
      working-directory: build-android
      run: ninja
