name: openbsd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: make
      uses: vmactions/openbsd-vm@v1.4.8
      with:
        prepare: |
          pkg_add \
            check \
            git \
            meson
        run: |
          git config --global --add safe.directory /home/runner/work/iodine/iodine
          meson setup build
          cd build
          ninja
          ninja test
