name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:
    strategy:
      matrix:
        # Enable tests, use SELinux, use systemd, use libcap-ng
        dep: [check, libselinux1-dev, libsystemd-dev, libcap-ng-dev]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: install deps
      run: sudo apt install meson ninja-build ${{ matrix.dep }}
    - name: meson setup
      run: meson setup build
    - name: build
      working-directory: build
      run: ninja
    - name: run tests
      working-directory: build
      run: ninja test

  build-android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: install deps
      run: sudo apt install meson ninja-build check
    - name: meson setup
      run: meson setup build-android --cross-file .github/ubuntu-android-aarch64.ini
    - name: build
      working-directory: build-android
      run: ninja

  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: install deps
      run: sudo apt install meson ninja-build mingw-w64 mingw-w64-tools libz-mingw-w64-dev
    - name: meson setup
      run: meson setup build-windows --cross-file .github/ubuntu-windows-x86-64.ini
    - name: build
      working-directory: build-windows
      run: ninja
