name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-meson mingw-w64-x86_64-check
    - name: setup
      run: meson setup build
    - name: build
      working-directory: build
      run: ninja
