name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:
    strategy:
      matrix:
        runner: [windows-latest, windows-11-arm]

    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v7
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: false
        install: git mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-zlib mingw-w64-ucrt-x86_64-meson mingw-w64-ucrt-x86_64-check
    - name: setup
      run: meson setup build
    - name: build
      working-directory: build
      run: ninja
    - name: run tests
      working-directory: build
      run: ninja test
