name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
          - { sys: clang64, env: clang-x86_64 }

    steps:
    - uses: actions/checkout@v7
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: false
        install: |
          git
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-zlib
          mingw-w64-${{matrix.env}}-meson
          mingw-w64-${{matrix.env}}-check
    - name: setup
      run: meson setup build
    - name: build
      working-directory: build
      run: ninja
    - name: run tests
      working-directory: build
      run: ninja test
